name: Pull Request
description: Standard PR template
title: "PR: "
labels: ["needs-review"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Summary of changes
      placeholder: Describe your changes...
    validations:
      required: true
      
  - type: textarea
    id: testing
    attributes:
      label: Testing
      description: How did you test these changes?
    validations:
      required: true
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Code follows project standards
          required: true
        - label: Tests added/updated
          required: true
        - label: Documentation updated