name: Pull Request
description: Submit a pull request
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your changes
      placeholder: Describe your changes...
    validations:
      required: true
      
  - type: dropdown
    id: type
    attributes:
      label: Type of Change
      options:
        - Bug fix
        - New feature
        - Breaking change
        - Documentation update
    validations:
      required: true
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have tested these changes
          required: true
        - label: My code follows style guidelines
          required: true