name: Deploy Multiple APIs to Azure App Services

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      api1-path: ${{ steps.publish-api1.outputs.artifact-path }}
      api2-path: ${{ steps.publish-api2.outputs.artifact-path }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Publish Api1
      id: publish-api1
      run: |
        dotnet publish src/CreditCard/CreditCard.csproj -c Release -o ${{ github.workspace }}/publish/creditcard
        echo "artifact-path=${{ github.workspace }}/publish/creditcard" >> $GITHUB_OUTPUT

    - name: Upload CreditCard artifact
      uses: actions/upload-artifact@v3
      with:
        name: creditcard-artifact
        path: ${{ github.workspace }}/publish/creditcard

    - name: Publish CreditBureau
      id: publish-creditbureau
      run: |
        dotnet publish src/CreditBureau/CreditBureau.csproj -c Release -o ${{ github.workspace }}/publish/creditbureau
        echo "artifact-path=${{ github.workspace }}/publish/creditbureau" >> $GITHUB_OUTPUT

    - name: Upload CreditBureau artifact
      uses: actions/upload-artifact@v3
      with:
        name: creditbureau-artifact
        path: ${{ github.workspace }}/publish/creditbureau

  deploy-creditbureau:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download CreditCard artifact
      uses: actions/download-artifact@v3
      with:
        name: creditcard-artifact
        path: ${{ github.workspace }}/publish/creditcard

    - name: Deploy CreditCard to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME_API1 }}
        publish-profile: ${{ format('{{0}} ${{1}} ${{2}}', secrets.AZURE_PUBLISH_URL_API1, secrets.AZURE_PUBLISH_USERNAME_API1, secrets.AZURE_PUBLISH_PASSWORD_API1) }}
        package: ${{ github.workspace }}/publish/creditcard

  deploy-creditbureau:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download creditbureau artifact
      uses: actions/download-artifact@v3
      with:
        name: creditbureau-artifact
        path: ${{ github.workspace }}/publish/creditbureau

    - name: Deploy creditbureau to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME_API2 }}
        publish-profile: ${{ format('{{0}} ${{1}} ${{2}}', secrets.AZURE_PUBLISH_URL_API2, secrets.AZURE_PUBLISH_USERNAME_API2, secrets.AZURE_PUBLISH_PASSWORD_API2) }}
        package: ${{ github.workspace }}/publish/creditbureau